### ISSUE TITLE
Login is not working after simulator is reset

### ISSUE THREAD

**Issue by billyean** [IOSPartyPlanner/PartyPlanner#39] opened 2017-05-14 19:01 UTC
After simulator is reset, I do login, the login page show blank page.

Here is the log:

2017-05-14 11:59:45.527 iOS-PartyPlanner[9840:646496] Falling back to loading access token from NSUserDefaults because of simulator bug
2017-05-14 11:59:45.527 iOS-PartyPlanner[9840:646496] Falling back to storing access token in NSUserDefaults because of simulator bug
2017-05-14 11:59:45.528 iOS-PartyPlanner[9840:646496] Falling back to loading access token from NSUserDefaults because of simulator bug
2017-05-14 11:59:45.528 iOS-PartyPlanner[9840:646496] Falling back to storing access token in NSUserDefaults because of simulator bug
2017-05-14 11:59:45.529 iOS-PartyPlanner[9840:646496] Falling back to loading access token from NSUserDefaults because of simulator bug
2017-05-14 11:59:45.529 iOS-PartyPlanner[9840:646496] Falling back to storing access token in NSUserDefaults because of simulator bug
2017-05-14 11:59:45.542 iOS-PartyPlanner[9840] <Notice> [Firebase/Messaging][I-IID001001] FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
current user nil
2017-05-14 11:59:45.835842-0700 iOS-PartyPlanner[9840:646496] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/hyan/Library/Developer/CoreSimulator/Devices/BF946BC8-6294-4E76-A0A0-457BA9789259/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-05-14 11:59:45.836369-0700 iOS-PartyPlanner[9840:646496] [MC] Reading from private effective user settings.
2017-05-14 11:59:46.308 iOS-PartyPlanner[9840] <Warning> [Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
2017-05-14 11:59:46.308 iOS-PartyPlanner[9840] <Notice> [Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
2017-05-14 11:59:47.233936-0700 iOS-PartyPlanner[9840:646496] [ViewService] Failed to get remote view controller with error: Error: domain=_UIViewServiceInterfaceErrorDomain, code=0

**Comment by una-020** [comment] 2017-05-15 00:24
Closing for now since the issue isnt seen. We can reopen once the issue resurfaces.!

**Closed as completed by una-020** 2017-05-15 00:24 UTC
